### ISSUE TITLE
Handling data persistence in the application

### ISSUE THREAD

**Issue by ainsleyh** [ainsleyh/BeaconAndEggs#8]

**Comment by httpNick** [comment]
I think this may be complete. I added the database helper a few days ago which can store a user's list of items. Is there more data that needs to persist?

**Comment by ainsleyh** [comment]
Awesome, Nick! I think only the item id needs to be persisted, since we are populating the item & category list from json data which we still have to do. Im going to need your help on the map view, but it is blocked until the add/search and the list view is complete.
